(let ((y 20))
  (fix ((fact (lambda (x) (if (zero? x) 1 (* x (fact (- x 1)))))))
       (let ((z 5000))
         (fix ((rec (lambda (z)
                      (if (zero? z) (fact y) ((lambda (s) (rec (- z 1))) (fact y))))))
              (time (rec z))))))
