(time (display
  (((lambda (f) (lambda (y) ((f f) y)))
    (lambda (rec)
      (lambda (x)
        (if (zero? x)
            (((lambda (f) (lambda (y) ((f f) y)))
              (lambda (g) (lambda (x) (if (zero? x) 1 (* x ((g g) (- x 1))))))) 20) 
            ((lambda (y) ((rec rec) (- x 1)))
             (((lambda (f) (lambda (y) ((f f) y)))
               (lambda (g) (lambda (x) (if (zero? x) 1 (* x ((g g) (- x 1))))))) 20))))
      ))
   5000)))
