#!/bin/bash

tests=`ls *rkt`
num=1
function run_test {
    echo $1 $2
    for i in {1..$num}
    do
        $1 $2 #| sed -r 's/.*cpu time: ([0-9]+).*/\1/' >> ./test-data/$3-$4.csv
    done
}


echo "running firstclass:"
t=$1
echo "$t:"
run_test ../target-c $t firstclass $t
run_test ../../pycket/pycket-c $t pycket $t
run_test racket $t racket $t

