#!/bin/bash

# tests=`ls *rkt`
# rm -r ./test-data
# mkdir test-data
function run_test {
    echo $1 $2
    echo "" > ./test-data/$3-$4.csv
    for i in {1..5}
    do
        $1 $2 | grep "cpu time" | sed -r 's/.*cpu time: ([0-9]+).*/\1/' >> ./test-data/$3-$4.csv
    done
}
tests="ack cpstak fib sum tak"

echo "running firstclass:"
for t in $tests
do
    echo "$t:"
    run_test ../target-c $t.rkt firstclass $t
    run_test ../../pycket/pycket-c $t.rkt pycket $t
    run_test racket $t.rkt racket $t
    echo "running with firstclass environment"
    run_test ../target-c $t\_fenv.rkt firstclass-fenv $t
    
done
